apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoservice-api
  namespace: autoservice
  labels:
    app: autoservice-api
  annotations:
    # Preencher com output Terraform `app_irsa_role_arn` após apply de infra-k8s
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/autoservicemanager-ENV-app-irsa"
automountServiceAccountToken: true
