apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoservice-migrate
  namespace: autoservice
  labels:
    app: autoservice-migrate
  annotations:
    # Preencher com output Terraform `migrate_irsa_role_arn` após apply de infra-k8s
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/autoservicemanager-ENV-migrate-irsa"
automountServiceAccountToken: true
